### ISSUE TITLE
History

### ISSUE THREAD

**Issue by PeterTippett** [XeroAPI/xerogolang#19]
Accessing History data for records seems to be missing from this unless I'm going blind.

**Comment by PeterTippett** [comment]
I've only done this for Contacts for my new project while waiting for Microsoft Excel update. This really needs to be done as a general call as applies across many resources which I'm not in a hurry for.

**Comment by TheRegan** [comment]
#29 Adds this functionality to the SDK.  There is an example of how to use it with invoices in the example project.  :-)
