### ISSUE TITLE
Transactional operation within session

### ISSUE THREAD

**Issue by febytanzil** [XeroAPI/xerogolang#26]
Hi,

In the case of error happened during creating multiple items in Xero,
would it be possible to rollback everything that I had created in Xero before?
Could be there a way to create transactional session with Xero like regular database operation?
e.g.
```
session, tx, err := provider.BeginTxAuth("")
...
defer tx.Rollback()

tx.CreateContact(session, ...)
tx.CreateInvoice(session, ...) // error here, then rollback create contact
tx.CreatePayment(session, ...)
...
tx.Commit() // commit all creations
```

Thanks

**Comment by TheRegan** [comment]
Hey there,  

This is outside the scope of what this SDK intends to provide.  I'd be interested to hear how you would implement this for yourself but it isn't something that we want to support in the SDK itself.

Cheers,

Regan.
