### ISSUE TITLE
Supporting multiple providers

### ISSUE THREAD

**Issue by xmarcoied** [XeroAPI/xerogolang#31]
Currently xerogolang only support one provider by default Name: xero. So, the used sessions and everything is related to the provider name. 

I was wondering what is the proper way to use the xerogolang package for multiple providers. 

I think about using SetName Method, to set a different names for each provider, and changing the GetSessionFromStore Method to get a session with a given name.

**Comment by TheRegan** [comment]
Can you please help me understand what the use case is for multiple providers? As written, the SDK is intended for use with only a single provider.  

We're effectively just extending https://github.com/markbates/goth which does support multiple providers though.  When I think of multiple providers, I am thinking about multiple APIs behind multiple auth mechanisms though so I'm keen to hear if your interpretation is different. :-)
