### ISSUE TITLE
API keys problems

### ISSUE THREAD

**Issue by ramonmacias** [XeroAPI/xerogolang#35]
Hi,

Do you know if for use this SDK you need to have a paid account for Xero? or can works using the free trial account? because I don't know why but I can not access to https://developer.xero.com/ my app section in order to generate the new api key.

Can anyone help me?

Thanks

**Comment by TheRegan** [comment]
You don't need a paid account to setup an api key.   Send an email to api@xero.com and they'll help you out.  :-)

**Comment by ramonmacias** [comment]
Ok thanks, I wrote them, let's see if can helps
