### ISSUE TITLE
Budget Summary Report

### ISSUE THREAD

**Issue by tuanphongvo** [XeroAPI/xerogolang#6]
Dear Team, 
I have an issue when pickup data with RunBudgetSummary function.
It didn't support querystringParameters for get old the reports.
Could you add the parameter in the functions?
It will many helpful.
Thanks

**Comment by TheRegan** [comment]
Thanks for finding this,  it was an oversight on my part.

I've added the ability to add querystring parameters to the RunBudgetSummary function now.  :-)
