### ISSUE TITLE
Custom layout in the Profilt and Lost reports

### ISSUE THREAD

**Issue by tuanphongvo** [XeroAPI/xerogolang#9]
I have an issue with custom layout in the Profit and Loss report.
The child Sections allocated incorrect. All of them have moved to root of report?
Example: 
Less Operating Expenses
+++ATM

The SDK pickup:

Less Operating Expenses
ATM

Thank for your help

**Comment by TheRegan** [comment]
Can you please provide the XML or JSON of the custom layout Profit & Loss report?

**Comment by tuanphongvo** [comment]
I was get report with the JSON type

**Comment by TheRegan** [comment]
Could you please provide the JSON of the report that is causing the issue?

**Comment by TheRegan** [comment]
You can get a raw response by using our API previewer tool: https://app.xero.com/Preview/Organisation

**Comment by tuanphongvo** [comment]
{
  "Id": "0d591a21-da2f-4707-ba11-a36240bd6c19",
  "Status": "OK",
  "ProviderName": "Xero API Previewer",
  "DateTimeUTC": "\/Date(1513827157885)\/",
  "Reports": [
    {
      "ReportID": "ProfitAndLoss",
      "ReportName": "Profit and Loss",
      "ReportType": "ProfitAndLoss",
      "ReportTitles": [
        "Profit & Loss",
        "Sample Community Bank #2",
        "1 April 2016 to 30 April 2016"
      ],
      "ReportDate": "21 December 2017",
      "UpdatedDateUTC": "\/Date(1513827157885)\/",
      "Fields": [],
      "Rows": [
        {
          "RowType": "Header",
          "Cells": [
            {
              "Value": ""
            },
            {
              "Value": "30 Apr 16"
            }
          ]
        },
        {
          "RowType": "Section",
          "Title": "Income",
          "Rows": [
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Fee Income",
                  "Attributes": [
                    {
                      "Value": "3a755ee8-c404-4554-987f-53c94ddcfc1f",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "11296.12",
                  "Attributes": [
                    {
                      "Value": "3a755ee8-c404-4554-987f-53c94ddcfc1f",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Gross Margin",
                  "Attributes": [
                    {
                      "Value": "62800486-de60-4826-9586-887aa310ea3d",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "81615.18",
                  "Attributes": [
                    {
                      "Value": "62800486-de60-4826-9586-887aa310ea3d",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Trailer Product Commission",
                  "Attributes": [
                    {
                      "Value": "a56fd6ca-718a-4f02-8b67-767891a9201f",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "25961.28",
                  "Attributes": [
                    {
                      "Value": "a56fd6ca-718a-4f02-8b67-767891a9201f",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Upfront Product Commission",
                  "Attributes": [
                    {
                      "Value": "b29afed7-fac2-4930-8849-5a76833801f1",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "2378.28",
                  "Attributes": [
                    {
                      "Value": "b29afed7-fac2-4930-8849-5a76833801f1",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "SummaryRow",
              "Cells": [
                {
                  "Value": "Total Income"
                },
                {
                  "Value": "121250.86"
                }
              ]
            }
          ]
        },
        {
          "RowType": "Section",
          "Title": "",
          "Rows": [
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Gross Profit"
                },
                {
                  "Value": "121250.86"
                }
              ]
            }
          ]
        },
        {
          "RowType": "Section",
          "Title": "Plus Other Income",
          "Rows": [
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Market Development Fund",
                  "Attributes": [
                    {
                      "Value": "7a56fa0d-1089-4522-9560-fa08b4b3677f",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "11230.98",
                  "Attributes": [
                    {
                      "Value": "7a56fa0d-1089-4522-9560-fa08b4b3677f",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "SummaryRow",
              "Cells": [
                {
                  "Value": "Total Other Income"
                },
                {
                  "Value": "11230.98"
                }
              ]
            }
          ]
        },
        {
          "RowType": "Section",
          "Title": "Less Operating Expenses",
          "Rows": [
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Agent Commission",
                  "Attributes": [
                    {
                      "Value": "9ee9501b-37e4-40be-9bbf-ab6f3401b46a",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "1141.62",
                  "Attributes": [
                    {
                      "Value": "9ee9501b-37e4-40be-9bbf-ab6f3401b46a",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Bad Debts Written Off",
                  "Attributes": [
                    {
                      "Value": "38383f18-fe35-4af6-8cde-84d19fac05fa",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "-1.84",
                  "Attributes": [
                    {
                      "Value": "38383f18-fe35-4af6-8cde-84d19fac05fa",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Board Expenses",
                  "Attributes": [
                    {
                      "Value": "4d15aeed-61a5-499b-9f1a-c2f26c2a4bdb",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "100.00",
                  "Attributes": [
                    {
                      "Value": "4d15aeed-61a5-499b-9f1a-c2f26c2a4bdb",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Cash Delivery",
                  "Attributes": [
                    {
                      "Value": "a626e406-cb5c-47c6-9e97-9ba22e4419b8",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "1106.28",
                  "Attributes": [
                    {
                      "Value": "a626e406-cb5c-47c6-9e97-9ba22e4419b8",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Cash Management",
                  "Attributes": [
                    {
                      "Value": "9a3987be-3019-4230-9997-6f41f56cc35e",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "91.70",
                  "Attributes": [
                    {
                      "Value": "9a3987be-3019-4230-9997-6f41f56cc35e",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Cleaning",
                  "Attributes": [
                    {
                      "Value": "71265df5-92d1-490c-9f0d-918ac4cbaf70",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "1404.12",
                  "Attributes": [
                    {
                      "Value": "71265df5-92d1-490c-9f0d-918ac4cbaf70",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Credit Checks / Search Fees",
                  "Attributes": [
                    {
                      "Value": "98ed5673-d56d-4d9c-ba6c-ed7b94777762",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "91.04",
                  "Attributes": [
                    {
                      "Value": "98ed5673-d56d-4d9c-ba6c-ed7b94777762",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Electricity & Gas",
                  "Attributes": [
                    {
                      "Value": "e49cf5e5-95eb-4d66-98ec-d304a5b89eab",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "3577.30",
                  "Attributes": [
                    {
                      "Value": "e49cf5e5-95eb-4d66-98ec-d304a5b89eab",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Freight, Cartage and Delivery",
                  "Attributes": [
                    {
                      "Value": "c83764a0-3457-4527-b5be-3d851e2b52ae",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "1661.74",
                  "Attributes": [
                    {
                      "Value": "c83764a0-3457-4527-b5be-3d851e2b52ae",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Insurance",
                  "Attributes": [
                    {
                      "Value": "f18ff2ea-9945-4293-8884-c463dfb6faaa",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "935.62",
                  "Attributes": [
                    {
                      "Value": "f18ff2ea-9945-4293-8884-c463dfb6faaa",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "IT Equipment Lease",
                  "Attributes": [
                    {
                      "Value": "d24d5aa9-d926-4227-8416-2709aa9963ce",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "872.72",
                  "Attributes": [
                    {
                      "Value": "d24d5aa9-d926-4227-8416-2709aa9963ce",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "IT Running Costs",
                  "Attributes": [
                    {
                      "Value": "79e524a3-4279-43cc-9ffb-1697325f4f80",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "1459.10",
                  "Attributes": [
                    {
                      "Value": "79e524a3-4279-43cc-9ffb-1697325f4f80",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "IT Support Costs",
                  "Attributes": [
                    {
                      "Value": "01d57c54-0e6e-48f3-b759-2ccc432b141c",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "880.90",
                  "Attributes": [
                    {
                      "Value": "01d57c54-0e6e-48f3-b759-2ccc432b141c",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "NSX Expenses",
                  "Attributes": [
                    {
                      "Value": "951094f7-1a72-41ad-a0bf-218313c82ec5",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "916.68",
                  "Attributes": [
                    {
                      "Value": "951094f7-1a72-41ad-a0bf-218313c82ec5",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Other Employer Expenses",
                  "Attributes": [
                    {
                      "Value": "c4acbc8e-145a-45f7-ac2c-d96feb383f8a",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "3198.44",
                  "Attributes": [
                    {
                      "Value": "c4acbc8e-145a-45f7-ac2c-d96feb383f8a",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Payroll Tax",
                  "Attributes": [
                    {
                      "Value": "31915788-b08c-4f2b-afb9-e99c2d30f7ef",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "2348.16",
                  "Attributes": [
                    {
                      "Value": "31915788-b08c-4f2b-afb9-e99c2d30f7ef",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Printing and Stationery",
                  "Attributes": [
                    {
                      "Value": "d78735d7-e566-4f95-86cb-bb273a575af9",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "1155.40",
                  "Attributes": [
                    {
                      "Value": "d78735d7-e566-4f95-86cb-bb273a575af9",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Procedural Errors",
                  "Attributes": [
                    {
                      "Value": "df4ab8ef-1a0e-45f1-b0c3-36dce2ad5ce0",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "100.00",
                  "Attributes": [
                    {
                      "Value": "df4ab8ef-1a0e-45f1-b0c3-36dce2ad5ce0",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Provision for Annual Leave Exp",
                  "Attributes": [
                    {
                      "Value": "b85743bc-9951-4af0-bbcb-6687711ef8d4",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "3500.20",
                  "Attributes": [
                    {
                      "Value": "b85743bc-9951-4af0-bbcb-6687711ef8d4",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Provision for Long Service Leave Exp",
                  "Attributes": [
                    {
                      "Value": "c61e72fc-cb6f-4d9f-8075-4491d0382873",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "236.44",
                  "Attributes": [
                    {
                      "Value": "c61e72fc-cb6f-4d9f-8075-4491d0382873",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Security Monitoring",
                  "Attributes": [
                    {
                      "Value": "b9743c66-4a14-4513-998e-f800f6966324",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "130.00",
                  "Attributes": [
                    {
                      "Value": "b9743c66-4a14-4513-998e-f800f6966324",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Staff Allowances",
                  "Attributes": [
                    {
                      "Value": "3de8ffa5-f5e3-49fc-9444-02db85d2a49b",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "1644.14",
                  "Attributes": [
                    {
                      "Value": "3de8ffa5-f5e3-49fc-9444-02db85d2a49b",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Staff Amenities",
                  "Attributes": [
                    {
                      "Value": "e1921984-8fa1-4c33-8a9b-58ca573b8ad8",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "63.64",
                  "Attributes": [
                    {
                      "Value": "e1921984-8fa1-4c33-8a9b-58ca573b8ad8",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Staff Training",
                  "Attributes": [
                    {
                      "Value": "d0bca0eb-90bb-4fdf-8bbb-44b467fe1266",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "11000.00",
                  "Attributes": [
                    {
                      "Value": "d0bca0eb-90bb-4fdf-8bbb-44b467fe1266",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Staff Uniforms",
                  "Attributes": [
                    {
                      "Value": "3845eb83-5bd9-4837-8295-cbffe6841442",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "-289.00",
                  "Attributes": [
                    {
                      "Value": "3845eb83-5bd9-4837-8295-cbffe6841442",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Superannuation",
                  "Attributes": [
                    {
                      "Value": "5f3c18fc-0e10-4543-a647-8702bbfd75e4",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "3406.10",
                  "Attributes": [
                    {
                      "Value": "5f3c18fc-0e10-4543-a647-8702bbfd75e4",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Telephone",
                  "Attributes": [
                    {
                      "Value": "bb3da545-d12e-4d9a-97c4-155322277ccd",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "301.82",
                  "Attributes": [
                    {
                      "Value": "bb3da545-d12e-4d9a-97c4-155322277ccd",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Wages & Salaries",
                  "Attributes": [
                    {
                      "Value": "83230b95-deff-451a-9391-f44b6796067b",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "35241.30",
                  "Attributes": [
                    {
                      "Value": "83230b95-deff-451a-9391-f44b6796067b",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Workers' Compensation",
                  "Attributes": [
                    {
                      "Value": "6cc613b6-3356-4866-beb9-84b496b62662",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "248.50",
                  "Attributes": [
                    {
                      "Value": "6cc613b6-3356-4866-beb9-84b496b62662",
                      "Id": "account"
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "RowType": "Section",
          "Title": "ATM",
          "Rows": [
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "ATM - Cash Delivery",
                  "Attributes": [
                    {
                      "Value": "a5c49ce5-1073-4862-88ef-fca1d18e3afa",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "501.46",
                  "Attributes": [
                    {
                      "Value": "a5c49ce5-1073-4862-88ef-fca1d18e3afa",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "ATM - Discrepancies",
                  "Attributes": [
                    {
                      "Value": "453cf4a2-3d46-4fbf-99c3-faff02c92843",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "63.64",
                  "Attributes": [
                    {
                      "Value": "453cf4a2-3d46-4fbf-99c3-faff02c92843",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "ATM - Leasing",
                  "Attributes": [
                    {
                      "Value": "57f31505-7acd-4ff8-9d5f-9b1087db5337",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "577.20",
                  "Attributes": [
                    {
                      "Value": "57f31505-7acd-4ff8-9d5f-9b1087db5337",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "ATM - Maintenance",
                  "Attributes": [
                    {
                      "Value": "2bf767aa-2121-4d26-8a08-d79da00019ed",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "190.82",
                  "Attributes": [
                    {
                      "Value": "2bf767aa-2121-4d26-8a08-d79da00019ed",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "ATM - Switching Fees",
                  "Attributes": [
                    {
                      "Value": "3bd997a6-6e80-459f-a4ee-710b7117bd5f",
                      "Id": "account"
                    }
                  ]
                },
                {
                  "Value": "66.40",
                  "Attributes": [
                    {
                      "Value": "3bd997a6-6e80-459f-a4ee-710b7117bd5f",
                      "Id": "account"
                    }
                  ]
                }
              ]
            },
            {
              "RowType": "SummaryRow",
              "Cells": [
                {
                  "Value": "Total ATM"
                },
                {
                  "Value": "1399.52"
                }
              ]
            }
          ]
        },
        {
          "RowType": "Section",
          "Title": "",
          "Rows": [
            {
              "RowType": "SummaryRow",
              "Cells": [
                {
                  "Value": "Total Operating Expenses"
                },
                {
                  "Value": "77921.64"
                }
              ]
            }
          ]
        },
        {
          "RowType": "Section",
          "Title": "",
          "Rows": [
            {
              "RowType": "Row",
              "Cells": [
                {
                  "Value": "Net Profit"
                },
                {
                  "Value": "54560.20"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

**Comment by tuanphongvo** [comment]
Hello Team,
Any updating for this issue?

Thanks.

**Comment by TheRegan** [comment]
This does not appear to be an issue with the SDK. In the JSON you've sent me 'ATM' appears as a section at the same level as 'Less Operating Expenses' and so the SDK is correctly processing the JSON file as you've described.

If you believe that this should be returned differently by the API then please log a support ticket here: [](https://developer.xero.com/contact-xero-developer-platform-support/)
